import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const initialCases = [
  { id: 'SLA-1842', customer: 'Acme Logistics', type: 'Priority support', remaining: '18m', owner: 'N. Mokoena', risk: 'Critical' },
  { id: 'SLA-1839', customer: 'Northstar Health', type: 'Incident response', remaining: '42m', owner: 'J. Patel', risk: 'High' },
  { id: 'SLA-1836', customer: 'Orbital Finance', type: 'Data request', remaining: '1h 35m', owner: 'L. Mensah', risk: 'Medium' },
  { id: 'SLA-1831', customer: 'Mosaic Retail', type: 'Technical support', remaining: '2h 18m', owner: 'K. Dlamini', risk: 'Low' }
]

function Brand() { return <span className="brand"><span className="brand-mark">S</span>stratum</span> }

function Dashboard({ onHome }) {
  const [cases, setCases] = useState(initialCases)
  const [filter, setFilter] = useState('All')
  const visibleCases = useMemo(() => filter === 'All' ? cases : cases.filter(item => item.risk === filter), [cases, filter])
  const addCase = () => setCases([{ id: `SLA-${1843 + cases.length}`, customer: 'New support case', type: 'Needs triage', remaining: '3h 00m', owner: 'Unassigned', risk: 'Medium' }, ...cases])
  return <main className="app-shell"><header className="app-nav"><button className="brand-button" onClick={onHome}><Brand /></button><div className="app-nav-links"><span className="selected">Overview</span><span>Cases</span><span>Reports</span></div><button className="back-link" onClick={onHome}>← Home</button></header><section className="dashboard-head"><div><p className="eyebrow">Tuesday, 11 July</p><h1>Good morning, Luthando.</h1><p>Here’s the service work that needs your attention today.</p></div><button className="button-dark" onClick={addCase}>Add case</button></section><section className="metrics"><article><span>Open cases</span><strong>{cases.length}</strong><small>Across all active queues</small></article><article><span>At risk</span><strong>2</strong><small>Need action in the next hour</small></article><article><span>Within target</span><strong>94%</strong><small>Last 30 days</small></article></section><section className="workspace"><div className="workspace-heading"><div><p className="eyebrow">Priority queue</p><h2>Cases to review</h2></div><div className="filters">{['All', 'Critical', 'High'].map(item => <button className={filter === item ? 'filter-active' : ''} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div></div><div className="case-table"><div className="table-labels"><span>Customer</span><span>Owner</span><span>Time remaining</span><span>Risk</span></div>{visibleCases.map(item => <div className="case-row" key={item.id}><div><strong>{item.customer}</strong><span>{item.id} · {item.type}</span></div><span>{item.owner}</span><span>{item.remaining}</span><span className={`risk ${item.risk.toLowerCase()}`}>{item.risk}</span></div>)}{visibleCases.length === 0 && <p className="empty-state">No cases match this filter.</p>}</div></section><section className="dashboard-note"><span>How Stratum works</span><p>Risk is based on case age, priority, customer sentiment, and support activity—so every signal is clear and explainable.</p></section></main>
}

function Landing({ onWorkspace }) {
  return <main className="landing-shell"><nav className="landing-nav"><a href="#top" aria-label="Stratum home"><Brand /></a><div className="nav-links"><a href="#product">Product</a><a href="#why">Why Stratum</a></div><button className="button-dark nav-button" onClick={onWorkspace}>Open workspace <span>↗</span></button></nav><section className="landing-hero" id="top"><p className="eyebrow">SLA intelligence for support teams</p><h1>Keep every<br/>service promise.</h1><p className="hero-sub">Stratum helps support teams see SLA risk early, focus their attention, and move with confidence.</p><div className="hero-actions"><button className="button-dark" onClick={onWorkspace}>Explore the workspace <span>↗</span></button><a href="#why">See how it works <span>↓</span></a></div></section><section className="product-band" id="product"><div className="product-intro"><p className="eyebrow">One clear view</p><h2>Know what needs attention before it becomes a breach.</h2><p>Stratum brings the right support signals into a calm, prioritised workspace.</p></div><div className="product-preview"><div className="preview-top"><Brand /><span>Today</span></div><div className="preview-content"><div className="preview-title"><div><p>Priority queue</p><h3>Cases to review</h3></div><button onClick={onWorkspace}>Open dashboard ↗</button></div><div className="preview-metrics"><div><span>Open cases</span><b>142</b></div><div><span>At risk</span><b>08</b></div><div><span>Within target</span><b>94%</b></div></div><div className="preview-row"><div><strong>Acme Logistics</strong><span>SLA-1842 · Priority support</span></div><em>18m remaining</em><i>Critical</i></div><div className="preview-row"><div><strong>Northstar Health</strong><span>SLA-1839 · Incident response</span></div><em>42m remaining</em><i>High</i></div></div></div></section><section className="benefits" id="why"><article><span>01</span><h2>See risk early.</h2><p>Bring urgency, age, activity, and sentiment into one simple signal.</p></article><article><span>02</span><h2>Focus the team.</h2><p>Keep everyone aligned on the cases that matter most right now.</p></article><article><span>03</span><h2>Stay on target.</h2><p>Build a steady, reliable service experience your customers can trust.</p></article></section><section className="closing"><p className="eyebrow">Service, in control</p><h2>A calmer way to run support.</h2><button className="button-dark" onClick={onWorkspace}>Open your workspace <span>↗</span></button></section></main>
}

function App() { const [view, setView] = useState('landing'); return view === 'dashboard' ? <Dashboard onHome={() => setView('landing')} /> : <Landing onWorkspace={() => setView('dashboard')} /> }

createRoot(document.getElementById('root')).render(<App />)
